name: Go-fmt
on: push
jobs:
  gofmt:
    name: Go fmt project
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: go fmt project
        uses: Jerome1337/gofmt-action@v1.0.2